services:
  frontend:
    restart: unless-stopped
    container_name: www.saeculum.net
    image: nginx:latest
    volumes:
      - ./www:/usr/share/nginx/www/
      - ./time:/usr/share/nginx/time/
      - ./assets:/usr/share/nginx/assets/
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 23888:8080
      - 23889:9080
