services:
  frontend:
    restart: unless-stopped
    container_name: www.saeculum.net
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 23888:80
